<?php

declare(strict_types=1);

namespace Laika\Engine\Tests\Unit;

use Composer\Composer;
use Composer\Config;
use Composer\IO\BufferIO;
use Composer\Script\Event;
use Laika\Engine\Cli\ScriptHandler;
use Laika\Engine\Queue\ScriptHandler as QueueScriptHandler;
use PHPUnit\Framework\TestCase;

/**
 * `php laika app:sync` owns entry-point generation now, and EntryPointsTest
 * covers the generation itself. What is left here is the Composer adapter,
 * which still has to work: a composer.json written before the move calls these
 * handlers, and Composer aborts the whole run on a handler that fails.
 *
 * Driven with a real Composer\Script\Event rather than a mock --
 * composer/composer is a require-dev and installed.
 */
final class ScriptHandlerTest extends TestCase
{
    private string $root;

    protected function setUp(): void
    {
        $this->root = sys_get_temp_dir() . '/laika-script-handler-' . bin2hex(random_bytes(6));

        mkdir($this->root . '/vendor', 0777, true);
        mkdir($this->root . '/lf-boot', 0777, true);
        file_put_contents($this->root . '/lf-boot/app.php', "<?php\n");
    }

    protected function tearDown(): void
    {
        $this->delete($this->root);
    }

    private function delete(string $path): void
    {
        if (!is_dir($path)) {
            is_file($path) && unlink($path);
            return;
        }

        foreach (array_diff((array) scandir($path), ['.', '..']) as $entry) {
            $this->delete($path . '/' . $entry);
        }

        rmdir($path);
    }

    /** A real Event, pointed at the temp root through its vendor-dir */
    private function event(?string $vendorDir = null): Event
    {
        $config = new Config(false, $this->root);
        $config->merge(['config' => ['vendor-dir' => $vendorDir ?? $this->root . '/vendor']]);

        $composer = new Composer();
        $composer->setConfig($config);

        return new Event('post-autoload-dump', $composer, new BufferIO());
    }

    private static function captured(Event $event): string
    {
        /** @var BufferIO $io */
        $io = $event->getIO();

        return $io->getOutput();
    }

    /*======================= THE PROJECT ROOT IT USES =======================*/

    public function testTheProjectRootIsTheParentOfTheVendorDir(): void
    {
        ScriptHandler::generate($this->event());

        self::assertFileExists($this->root . '/laika');
        self::assertFileExists($this->root . '/worker');
    }

    public function testACustomVendorDirStillResolvesTheProjectRoot(): void
    {
        // Composer lets a project rename vendor/, so the root cannot be assumed
        mkdir($this->root . '/libs', 0777, true);

        ScriptHandler::generate($this->event($this->root . '/libs'));

        self::assertFileExists($this->root . '/laika');
    }

    /*============================== ITS OUTPUT ==============================*/

    public function testBothFilesAreNamedInOneLineOfOutput(): void
    {
        $event = $this->event();
        ScriptHandler::generate($event);

        $output = self::captured($event);

        self::assertStringContainsString('laika', $output);
        self::assertStringContainsString('worker', $output);
        self::assertSame(1, substr_count(trim($output), "\n") + 1, 'Expected a single line.');
    }

    public function testAnUpToDateRunIsSilent(): void
    {
        ScriptHandler::generate($this->event());

        $event = $this->event();
        ScriptHandler::generate($event);

        self::assertSame('', self::captured($event));
    }

    public function testNothingIsSaidOutsideAProjectRoot(): void
    {
        unlink($this->root . '/lf-boot/app.php');

        $event = $this->event();
        ScriptHandler::generate($event);

        self::assertFileDoesNotExist($this->root . '/laika');
        self::assertSame('', self::captured($event));
    }

    public function testPruningIsReported(): void
    {
        file_put_contents($this->root . '/worker.bat', "@echo off\nrem Auto-generated by laikait/laika-queue\n");

        $event = $this->event();
        ScriptHandler::generate($event);

        self::assertStringContainsString('removed', self::captured($event));
    }

    /*========================= BACKWARD COMPATIBILITY =========================*/

    public function testTheDeprecatedQueueEntryStillGeneratesBoth(): void
    {
        // A project that lists only the old Queue handler must still work
        QueueScriptHandler::generate($this->event());

        self::assertFileExists($this->root . '/laika');
        self::assertFileExists($this->root . '/worker');
    }

    public function testListingBothEntriesWritesEachFileOnce(): void
    {
        // The shape of an un-migrated composer.json: the second call must find
        // both files already identical and stay silent
        ScriptHandler::generate($this->event());

        $second = $this->event();
        QueueScriptHandler::generate($second);

        self::assertSame('', self::captured($second));
    }
}
