<?php

declare(strict_types=1);

namespace Laika\Engine\Cli\Command;

use Laika\Engine\Cli\Contracts\CommandInterface;
use Laika\Engine\Cli\Stub;

class NginxServerCommand implements CommandInterface
{
    public function signature(): string
    {
        return 'nginx:server';
    }

    public function handle(array $args, string $basePath): int
    {
        if (count($args) > 7) {
            Message::suggestion($this->command());
            return 1;
        }

        $domain = (string) Argument::getValue('domain', $args, 'localhost');
        if (!preg_match('/^[a-z0-9_.\-* ]+$/i', $domain)) {
            Message::error("Invalid domain [{$domain}].");
            return 1;
        }

        $port = (string) Argument::getValue('port', $args, '80');
        if (!preg_match('/^\d{1,5}$/', $port) || (int) $port < 1 || (int) $port > 65535) {
            Message::error("Invalid port [{$port}].");
            return 1;
        }

        // Either an explicit upstream, or one derived from a PHP version
        $fastcgi = (string) Argument::getValue('fastcgi', $args, '');
        if ($fastcgi === '') {
            $php = (string) Argument::getValue('php', $args, implode('.', array_slice(explode('.', PHP_VERSION), 0, 2)));
            if (!preg_match('/^\d+\.\d+$/', $php)) {
                Message::error("Invalid PHP version [{$php}]. Example: --php=8.3");
                return 1;
            }
            $fastcgi = "unix:/var/run/php/php{$php}-fpm.sock";
        }

        // Defaults to this machine's project path, which is wrong when the
        // config is generated on one host and deployed to another.
        $root = (string) Argument::getValue('root', $args, $basePath);

        $content = Stub::render('nginx-server', [
            'domain'    =>  $domain,
            'port'      =>  $port,
            // nginx wants forward slashes even when the CLI runs on Windows
            'root'      =>  str_replace('\\', '/', rtrim($root, '/\\')),
            'fastcgi'   =>  $fastcgi,
            'upload'    =>  (string) Argument::getValue('upload', $args, '20M'),
            // Written into the block, not included from the project. The
            // block has to stand on its own: nginx.conf may not exist, may
            // be edited, and lives where the web server cannot count on it.
            'rules'     =>  $this->indent(Stub::load('nginx-rules'), 4),
        ]);

        $output = (string) Argument::getValue('output', $args, '');

        if ($output === '') {
            echo $content;
            Message::info('Pass --output=<path> to write this instead of printing it.');
            return 0;
        }

        // Never over the framework-managed file. nginx.conf is meant to be
        // included from inside a server { } block, so a server block written
        // there nests a server{} inside a server{} ("server directive is not
        // allowed here"), and it throws away the rules nginx:make generated.
        if ($this->isManagedConf($output, $basePath)) {
            Message::error('Refusing to overwrite the framework-managed nginx.conf.');
            Message::info('That file is generated by `php laika nginx:make` and is meant to be');
            Message::info('included from inside a server block, so a server block cannot live in');
            Message::info('it. This block is self-contained -- give it a file of its own:');
            Message::info('php laika nginx:server --output=/etc/nginx/sites-available/' . $domain);
            Message::info('Run `php laika nginx:make --force` if nginx.conf was already overwritten.');
            return 1;
        }

        try {
            Stub::write($output, $content);
        } catch (\Throwable $th) {
            Message::error($th->getMessage());
            return 1;
        }

        Message::success("Server block written to {$output}.");
        Message::info('Check it before reloading: nginx -t && systemctl reload nginx');

        return 0;
    }

    /**
     * Indent Every Non-Empty Line Of A Block
     *
     * The rules stub is shared with nginx:make, which writes it at column 0.
     * Inside the server block it has to sit one level in. Blank lines are
     * left blank rather than padded with trailing spaces.
     *
     * @param string $block Text to indent
     * @param int $spaces Width of one level
     * @return string
     */
    protected function indent(string $block, int $spaces): string
    {
        $pad = str_repeat(' ', $spaces);

        $lines = array_map(
            static fn (string $line): string => trim($line) === '' ? '' : $pad . $line,
            explode("\n", rtrim($block))
        );

        return implode("\n", $lines);
    }

    /**
     * Is This Path The nginx.conf That nginx:make Manages
     *
     * Compared after realpath() where the file exists, so "./nginx.conf",
     * "nginx.conf" and an absolute path all resolve to the same answer. A path
     * that does not exist yet is compared as written, against the same name in
     * the project root.
     *
     * @param string $output Path as the caller wrote it
     * @param string $basePath Project root
     * @return bool
     */
    protected function isManagedConf(string $output, string $basePath): bool
    {
        $managed = $basePath . DIRECTORY_SEPARATOR . 'nginx.conf';
        $real = realpath($output);

        if ($real !== false) {
            return $real === (realpath($managed) ?: $managed);
        }

        // Not on disk yet: resolve it against the working directory the way
        // the write itself will
        $candidate = preg_match('#^(?:[a-zA-Z]:[\\\\/]|[\\\\/])#', $output) === 1
            ? $output
            : getcwd() . DIRECTORY_SEPARATOR . $output;

        return str_replace('\\', '/', $candidate) === str_replace('\\', '/', $managed);
    }

    public function command(): string
    {
        return "php laika nginx:server [--domain=example.com] [--port=80] [--php=8.3] [--fastcgi=...] [--root=/var/www/app] [--upload=20M] [--output=/etc/nginx/sites-available/example.com]";
    }

    public function help(): array
    {
        return [
            'signature'     =>  $this->signature(),
            'description'   =>  'Generate a complete, self-contained nginx server block for this project',
            'command'       =>  $this->command(),
            'inputs'        =>  [],
            'params'        =>  [
                                    'domain'    =>  'server_name value (default: localhost)',
                                    'port'      =>  'Listen port (default: 80)',
                                    'php'       =>  'PHP-FPM version used to build the socket path (default: this PHP)',
                                    'fastcgi'   =>  'Explicit upstream, overrides --php. Example: 127.0.0.1:9000',
                                    'root'      =>  'Project path on the target server, without /public (default: this machine\'s path)',
                                    'upload'    =>  'client_max_body_size (default: 20M)',
                                    'output'    =>  'Write the block to this path instead of printing it. Not the project\'s nginx.conf, which this block includes',
                                ]
        ];
    }
}
