<?php

declare(strict_types=1);

namespace Laika\Engine\Cli\Command;

use Laika\Engine\Cli\Contracts\CommandInterface;
class QueueWorkCommand implements CommandInterface
{
    public function signature(): string
    {
        return 'queue:work';
    }

    public function handle(array $args, string $basePath): int
    {
        if (count($args) > 1) {
            Message::suggestion($this->command());
            return 1;
        }

        $queue = $args[0] ?? 'default';

        // Prefer the project-root proxy (generated by QueuePlugin on
        // install), fall back to the package's own bin/worker directly —
        // same resolution the proxy itself would end up at either way.
        $script = "{$basePath}/worker";
        if (!is_file($script)) {
            $script = "{$basePath}/vendor/laikait/laika-engine/bin/worker";
        }
        if (!is_file($script)) {
            Message::error("Worker executable not found. Is [laikait/laika-engine] installed?");
            return 1;
        }

        echo "Starting worker on queue [{$queue}]. Press Ctrl+C to stop.\n\n";

        // Delegate rather than reimplement — this stays a thin proxy so it
        // can never drift from the real worker's driver-selection, signal
        // handling, and memory-limit logic (same idea as app:start
        // delegating to `php -S` instead of its own dev server).
        $command = sprintf('php %s %s', escapeshellarg($script), escapeshellarg($queue));
        passthru($command, $exitCode);

        return $exitCode;
    }

    public function command(): string
    {
        return "php laika queue:work [queue]";
    }

    public function help(): array
    {
        return [
            'signature'     =>  $this->signature(),
            'description'   =>  'Run the queue worker in the foreground',
            'command'       =>  $this->command(),
            'inputs'        =>  ['queue' => 'Queue name to work (default: "default")'],
            'params'        =>  []
        ];
    }
}
